apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  web
  labels:
    name:  web
spec:
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - image: nginx
        name:  web
        resources:
          limits:
            cpu: "250m"
            memory: "500M" 
      restartPolicy: Always
